package com.microfinance.service;

import com.microfinance.dto.RiskAssessmentResponse;
import com.microfinance.dto.RiskAssessmentSummaryRequest;
import com.microfinance.exception.BusinessException;
import com.microfinance.exception.ResourceNotFoundException;
import com.microfinance.model.Applicant;
import com.microfinance.model.LoanApplication;
import com.microfinance.model.LoanStatus;
import com.microfinance.model.RiskAssessment;
import com.microfinance.model.RiskStatus;
import com.microfinance.repository.ApplicantRepository;
import com.microfinance.repository.LoanApplicationRepository;
import com.microfinance.repository.RiskAssessmentRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class RiskAssessmentService {

    private final RiskAssessmentRepository riskAssessmentRepository;
    private final LoanApplicationRepository loanApplicationRepository;
    private final ApplicantRepository applicantRepository;
    private final LoanApplicationService loanApplicationService;

    /**
     * Centralized validation method for assessment eligibility.
     * Validates both input parameters and business rules.
     *
     * @param applicationId the application ID to validate
     * @throws BusinessException if validation fails
     * @throws ResourceNotFoundException if application/applicant not found
     */
    private void validateAssessmentEligibility(String applicationId) {
        // Validate input parameter
        if (applicationId == null || applicationId.trim().isEmpty()) {
            throw new BusinessException("Application ID is required for risk assessment");
        }

        // Load and validate application exists
        LoanApplication application = loanApplicationRepository.findById(applicationId)
                .orElseThrow(() -> new ResourceNotFoundException("Loan application not found with id: " + applicationId));

        // Load and validate applicant exists
        Applicant applicant = applicantRepository.findById(application.getApplicantId())
                .orElseThrow(() -> new ResourceNotFoundException("Applicant not found with id: " + application.getApplicantId()));

        // Validate application status - do not allow finalized applications
        if (application.getStatus() != null) {
            LoanStatus status = application.getStatus();
            if (status == LoanStatus.APPROVED || status == LoanStatus.REJECTED || status == LoanStatus.CANCELLED) {
                throw new BusinessException("Cannot assess risk for finalized applications. Status: " + status);
            }
        }

        // Validate required applicant fields
        if (applicant.getMonthlyIncome() == null) {
            throw new BusinessException("Applicant monthly income is required for risk assessment");
        }
        if (applicant.getMonthlyIncome() <= 0) {
            throw new BusinessException("Applicant monthly income must be greater than zero");
        }

        if (applicant.getEmploymentStatus() == null || applicant.getEmploymentStatus().trim().isEmpty()) {
            throw new BusinessException("Applicant employment status is required for risk assessment");
        }

        // NOTE: termMonths, interestRate, purpose, hasCoSigner are OPTIONAL
        // Applications can be created with just amount (Amount-Only Mode)
        // These fields will be generated by recommendation engine if not provided
        // Risk assessment uses available data; if missing, assessment still proceeds with applicant profile

        // Validate optional numeric fields that should not be negative
        if (applicant.getExistingLoans() != null && applicant.getExistingLoans() < 0) {
            throw new BusinessException("Existing loans count cannot be negative");
        }

        if (applicant.getDependents() != null && applicant.getDependents() < 0) {
            throw new BusinessException("Dependents count cannot be negative");
        }

        if (applicant.getMonthlyDebtPayment() != null && applicant.getMonthlyDebtPayment() < 0) {
            throw new BusinessException("Monthly debt payment cannot be negative");
        }
    }

    public RiskAssessmentResponse runAssessment(String applicationId) {
        try {
            validateAssessmentEligibility(applicationId);

            loanApplicationService.setRiskAssessmentInProgress(applicationId);

            LoanApplication application = loanApplicationRepository.findById(applicationId)
                    .orElseThrow(() -> new ResourceNotFoundException("Loan application not found with id: " + applicationId));

            Applicant applicant = applicantRepository.findById(application.getApplicantId())
                    .orElseThrow(() -> new ResourceNotFoundException("Applicant not found with id: " + application.getApplicantId()));

            archiveExistingAssessments(applicationId);

            RiskScoreResult result = calculateRiskScore(applicant, application);

            RiskAssessment assessment = new RiskAssessment();
            assessment.setApplicationId(applicationId);
            assessment.setApplicantId(application.getApplicantId());
            assessment.setApplicationNumber(application.getApplicationNumber());
            assessment.setApplicantNumber(applicant.getApplicantNumber());
            assessment.setRiskScore(result.getScore());
            assessment.setRiskLevel(result.getLevel());
            assessment.setStatus(RiskStatus.ASSESSED);
            assessment.setModelVersion("RULE_BASED_V1");
            assessment.setTopFactors(result.getTopFactors());
            assessment.setExplanationText(result.getExplanationText());
            assessment.setInputSnapshot(result.getInputSnapshot());

            Instant now = Instant.now();
            assessment.setAssessedAt(now);
            assessment.setCreatedAt(now);
            assessment.setUpdatedAt(now);

            System.out.println("Saving new risk assessment for application: " + applicationId);

            RiskAssessment savedAssessment = riskAssessmentRepository.save(assessment);

            if (savedAssessment == null || savedAssessment.getId() == null) {
                throw new BusinessException("Failed to save new risk assessment");
            }

            System.out.println("Saved risk assessment ID: " + savedAssessment.getId());

            RiskAssessmentSummaryRequest summaryRequest = new RiskAssessmentSummaryRequest();
            summaryRequest.setRiskAssessmentId(savedAssessment.getId());
            summaryRequest.setRiskScore(savedAssessment.getRiskScore());
            summaryRequest.setRiskLevel(savedAssessment.getRiskLevel());

            System.out.println("Updating application risk summary for application: " + applicationId);

            loanApplicationService.updateRiskAssessmentSummary(applicationId, summaryRequest);

            System.out.println("✓ Risk assessment completed for application " + applicationId);

            return toResponse(savedAssessment);

        } catch (BusinessException | ResourceNotFoundException e) {
            try {
                loanApplicationService.setRiskAssessmentFailed(applicationId, e.getMessage());
            } catch (Exception ignored) {
            }
            throw e;
        } catch (Exception e) {
            try {
                loanApplicationService.setRiskAssessmentFailed(applicationId, e.getMessage());
            } catch (Exception ignored) {
            }
            throw new BusinessException("Failed to run risk assessment: " + e.getMessage());
        }
    }

    /**
     * Archive all existing active assessments for an application.
     * This ensures clean re-assessment: old assessments don't interfere with new ones.
     */
    private void archiveExistingAssessments(String applicationId) {
        try {
            // Find all non-deleted assessments for this application
            List<RiskAssessment> existingAssessments = riskAssessmentRepository
                    .findByApplicationIdAndDeletedFalse(applicationId);

            for (RiskAssessment existing : existingAssessments) {
                // Mark as deleted (soft delete) instead of keeping it active
                existing.setDeleted(true);
                existing.setDeletedAt(Instant.now());
                existing.setDeletedBy("SYSTEM");
                existing.setDeleteReason("Archived due to re-assessment");
                riskAssessmentRepository.save(existing);

                System.out.println("  ℹ Archived previous assessment: " + existing.getId());
            }
        } catch (Exception e) {
            System.err.println("Warning: Failed to archive existing assessments for " + applicationId + ": " + e.getMessage());
            // Don't throw - let the new assessment proceed anyway
        }
    }

    public RiskAssessmentResponse getLatestByApplicationId(String applicationId) {
        // Validate input parameter
        if (applicationId == null || applicationId.trim().isEmpty()) {
            throw new BusinessException("Application ID is required");
        }

        try {
            // Primary method: Find latest by application ID
            RiskAssessment assessment = riskAssessmentRepository
                    .findTopByApplicationIdAndDeletedFalseOrderByAssessedAtDesc(applicationId)
                    .orElse(null);

            if (assessment != null) {
                return toResponse(assessment);
            }

            // Fallback: Try alternative ordering methods
            assessment = getLatestByApplicationIdFallback(applicationId);
            if (assessment != null) {
                return toResponse(assessment);
            }

            throw new ResourceNotFoundException("No risk assessment found for application: " + applicationId);

        } catch (ResourceNotFoundException e) {
            throw e; // Re-throw ResourceNotFoundException as-is
        } catch (Exception e) {
            // Log the error and try fallback methods
            System.err.println("Error in getLatestByApplicationId for app " + applicationId + ": " + e.getMessage());

            try {
                RiskAssessment fallbackAssessment = getLatestByApplicationIdFallback(applicationId);
                if (fallbackAssessment != null) {
                    return toResponse(fallbackAssessment);
                }
            } catch (Exception fallbackException) {
                System.err.println("Fallback method also failed: " + fallbackException.getMessage());
            }

            throw new ResourceNotFoundException("No risk assessment found for application: " + applicationId);
        }
    }

    /**
     * Fallback method to find latest risk assessment using alternative approaches
     */
    private RiskAssessment getLatestByApplicationIdFallback(String applicationId) {
        try {
            // Fallback 1: Find all assessments for the application and manually sort
            List<RiskAssessment> allAssessments = riskAssessmentRepository
                    .findByApplicationIdAndDeletedFalseOrderByAssessedAtDesc(applicationId);

            if (!allAssessments.isEmpty()) {
                return allAssessments.get(0); // Already sorted by assessedAt desc
            }

            // Fallback 2: Try ordering by createdAt if assessedAt is null
            allAssessments = riskAssessmentRepository
                    .findByApplicationIdAndDeletedFalseOrderByCreatedAtDesc(applicationId);

            if (!allAssessments.isEmpty()) {
                return allAssessments.get(0);
            }

            // Fallback 3: Get all and manually find the latest (in case of db issues)
            List<RiskAssessment> allUnsorted = riskAssessmentRepository
                    .findByApplicationIdAndDeletedFalse(applicationId);

            return allUnsorted.stream()
                    .max((a, b) -> {
                        if (a.getAssessedAt() != null && b.getAssessedAt() != null) {
                            return a.getAssessedAt().compareTo(b.getAssessedAt());
                        } else if (a.getCreatedAt() != null && b.getCreatedAt() != null) {
                            return a.getCreatedAt().compareTo(b.getCreatedAt());
                        } else if (a.getId() != null && b.getId() != null) {
                            return a.getId().compareTo(b.getId());
                        }
                        return 0;
                    })
                    .orElse(null);

        } catch (Exception e) {
            System.err.println("All fallback methods failed for application " + applicationId + ": " + e.getMessage());
            return null;
        }
    }

    /**
     * Get all risk assessments for an application with fallback logic
     */
    public List<RiskAssessmentResponse> getAllByApplicationId(String applicationId) {
        try {
            List<RiskAssessment> assessments = riskAssessmentRepository
                    .findByApplicationIdAndDeletedFalseOrderByAssessedAtDesc(applicationId);

            return assessments.stream()
                    .map(this::toResponse)
                    .collect(Collectors.toList());

        } catch (Exception e) {
            System.err.println("Error getting all assessments for application " + applicationId + ": " + e.getMessage());

            try {
                // Fallback: try alternative methods
                List<RiskAssessment> fallbackAssessments = riskAssessmentRepository
                        .findByApplicationIdAndDeletedFalse(applicationId);

                return fallbackAssessments.stream()
                        .map(this::toResponse)
                        .sorted((a, b) -> {
                            if (a.getAssessedAt() != null && b.getAssessedAt() != null) {
                                return b.getAssessedAt().compareTo(a.getAssessedAt());
                            } else if (a.getCreatedAt() != null && b.getCreatedAt() != null) {
                                return b.getCreatedAt().compareTo(a.getCreatedAt());
                            }
                            return 0;
                        })
                        .collect(Collectors.toList());

            } catch (Exception fallbackException) {
                System.err.println("Fallback method for getAllByApplicationId also failed: " + fallbackException.getMessage());
                return new ArrayList<>(); // Return empty list instead of throwing
            }
        }
    }

    public RiskAssessmentResponse getById(String id) {
        // Validate input parameter
        if (id == null || id.trim().isEmpty()) {
            throw new BusinessException("Risk assessment ID is required");
        }

        RiskAssessment assessment = riskAssessmentRepository.findByIdAndDeletedFalse(id)
                .orElseThrow(() -> new ResourceNotFoundException("Risk assessment not found with id: " + id));

        return toResponse(assessment);
    }

    public void deleteAssessment(String id, String deletedBy, String reason) {
        // Validate input parameters
        if (id == null || id.trim().isEmpty()) {
            throw new BusinessException("Risk assessment ID is required for deletion");
        }

        if (deletedBy == null || deletedBy.trim().isEmpty()) {
            throw new BusinessException("Deleted by user information is required");
        }

        // Load RiskAssessment by id
        RiskAssessment assessment = riskAssessmentRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Risk assessment not found with id: " + id));

        // Check if already deleted
        if (Boolean.TRUE.equals(assessment.getDeleted())) {
            throw new BusinessException("Risk assessment is already deleted");
        }

        // Set deleted fields
        assessment.setDeleted(true);
        assessment.setDeletedAt(Instant.now());
        assessment.setDeletedBy(deletedBy);
        assessment.setDeleteReason(reason);

        // Save the assessment
        riskAssessmentRepository.save(assessment);

        // Update related LoanApplication
        LoanApplication loanApplication = loanApplicationRepository.findById(assessment.getApplicationId())
                .orElse(null);

        if (loanApplication != null && id.equals(loanApplication.getRiskAssessmentId())) {
            // Clear the risk summary fields
            loanApplication.setRiskAssessmentId(null);
            loanApplication.setRiskScore(null);
            loanApplication.setRiskLevel(null);
            loanApplication.setRiskStatus(RiskStatus.NOT_ASSESSED);

            // Clear the recommendation summary fields (recommendations depend on risk assessment)
            loanApplication.setRecommendationId(null);
            loanApplication.setRecommendedAmount(null);
            loanApplication.setRecommendedPeriod(null);
            loanApplication.setRecommendedInterestRate(null);

            // Reset workflow status to pending since risk assessment is removed
            loanApplication.setStatus(LoanStatus.PENDING);

            // Save the loan application
            loanApplicationRepository.save(loanApplication);
        }
    }

    private RiskScoreResult calculateRiskScore(Applicant applicant, LoanApplication application) {
        double score = 0.30; // Base score
        List<String> topFactors = new ArrayList<>();
        Map<String, Object> inputSnapshot = new HashMap<>();

        // Capture input data
        inputSnapshot.put("monthlyIncome", applicant.getMonthlyIncome());
        inputSnapshot.put("existingLoans", applicant.getExistingLoans());
        inputSnapshot.put("dependents", applicant.getDependents());
        inputSnapshot.put("employmentStatus", applicant.getEmploymentStatus());
        inputSnapshot.put("employmentLengthMonths", applicant.getEmploymentLengthMonths());
        inputSnapshot.put("monthlyDebtPayment", applicant.getMonthlyDebtPayment());
        inputSnapshot.put("creditScore", applicant.getCreditScore());
        inputSnapshot.put("applicationAmount", application.getAmount());
        inputSnapshot.put("termMonths", application.getTermMonths());
        inputSnapshot.put("hasCoSigner", application.getHasCoSigner());

        // Safe double values with defaults
        double monthlyIncome = applicant.getMonthlyIncome() != null ? applicant.getMonthlyIncome() : 0;
        Integer existingLoans = applicant.getExistingLoans() != null ? applicant.getExistingLoans() : 0;
        Integer dependents = applicant.getDependents() != null ? applicant.getDependents() : 0;
        Double monthlyDebtPayment = applicant.getMonthlyDebtPayment() != null ? applicant.getMonthlyDebtPayment() : 0;
        Double loanAmount = application.getAmount() != null ? application.getAmount() : 0;
        String employmentStatus = normalizeEmploymentStatus(applicant.getEmploymentStatus());

        // Ensure values are not negative (defensive)
        monthlyIncome = Math.max(0, monthlyIncome);
        existingLoans = Math.max(0, existingLoans);
        dependents = Math.max(0, dependents);
        monthlyDebtPayment = Math.max(0, monthlyDebtPayment);
        loanAmount = Math.max(0, loanAmount);

        // Income-based scoring
        if (monthlyIncome < 50000) {
            score += 0.20;
            topFactors.add("Low monthly income increases risk");
        } else if (monthlyIncome > 150000) {
            score -= 0.10;
            topFactors.add("High monthly income reduces risk");
        }

        // Existing loans
        if (existingLoans >= 3) {
            score += 0.10;
            topFactors.add("Multiple existing loans increase risk");
        }

        // Dependents
        if (dependents >= 4) {
            score += 0.05;
            topFactors.add("High number of dependents increases risk");
        }

        // Employment status (normalized comparison)
        if ("UNEMPLOYED".equals(employmentStatus)) {
            score += 0.25;
            topFactors.add("Unemployment significantly increases risk");
        } else if ("SELF_EMPLOYED".equals(employmentStatus)) {
            score += 0.10;
            topFactors.add("Self-employment increases risk");
        }

        // Employment length
        Integer employmentLength = applicant.getEmploymentLengthMonths() != null ? applicant.getEmploymentLengthMonths() : 0;
        if (employmentLength >= 24) {
            score -= 0.10;
            topFactors.add("Long employment history reduces risk");
        }

        // Debt-to-income ratio (safe calculation)
        if (monthlyIncome > 0) {
            double dti = monthlyDebtPayment / monthlyIncome;
            if (dti > 0.50) {
                score += 0.20;
                topFactors.add("Very high debt-to-income ratio increases risk");
            } else if (dti > 0.30) {
                score += 0.10;
                topFactors.add("High debt-to-income ratio increases risk");
            }
        }

        // Income to loan ratio (safe calculation)
        if (monthlyIncome > 0 && loanAmount > 0) {
            double incomeToLoan = loanAmount / monthlyIncome;
            if (incomeToLoan > 12) {
                score += 0.15;
                topFactors.add("Very high loan amount relative to income");
            } else if (incomeToLoan > 6) {
                score += 0.08;
                topFactors.add("High loan amount relative to income");
            }
        }

        // Co-signer
        if (Boolean.TRUE.equals(application.getHasCoSigner())) {
            score -= 0.10;
            topFactors.add("Co-signer reduces risk");
        }

        // Credit score
        if (applicant.getCreditScore() != null) {
            Integer creditScore = applicant.getCreditScore();
            if (creditScore < 450) {
                score += 0.20;
                topFactors.add("Very low credit score increases risk");
            } else if (creditScore < 600) {
                score += 0.10;
                topFactors.add("Low credit score increases risk");
            } else if (creditScore > 700) {
                score -= 0.05;
                topFactors.add("Good credit score reduces risk");
            }
        }

        // Clamp score between 0.01 and 0.99
        score = Math.max(0.01, Math.min(0.99, score));

        // Determine risk level
        String riskLevel;
        if (score < 0.25) {
            riskLevel = "LOW";
        } else if (score <= 0.50) {
            riskLevel = "MEDIUM";
        } else {
            riskLevel = "HIGH";
        }

        String explanationText = String.format("Risk assessment completed using current applicant and loan data. The result indicates %s risk.", riskLevel);

        return new RiskScoreResult(score, riskLevel, topFactors, explanationText, inputSnapshot);
    }

    /**
     * Normalizes employment status to uppercase for consistent comparisons.
     * Handles null, empty, and mixed-case values.
     *
     * @param employmentStatus the employment status from applicant
     * @return normalized employment status, or null if invalid
     */
    private String normalizeEmploymentStatus(String employmentStatus) {
        if (employmentStatus == null || employmentStatus.trim().isEmpty()) {
            return null;
        }
        return employmentStatus.trim().toUpperCase();
    }

    private RiskAssessmentResponse toResponse(RiskAssessment assessment) {
        RiskAssessmentResponse response = new RiskAssessmentResponse();
        response.setId(assessment.getId());
        response.setApplicationId(assessment.getApplicationId());
        response.setApplicantId(assessment.getApplicantId());
        response.setApplicationNumber(assessment.getApplicationNumber());
        response.setApplicantNumber(assessment.getApplicantNumber());
        response.setRiskScore(assessment.getRiskScore());
        response.setRiskLevel(assessment.getRiskLevel());
        response.setStatus(assessment.getStatus().name());
        response.setModelVersion(assessment.getModelVersion());
        response.setTopFactors(assessment.getTopFactors());
        response.setExplanationText(assessment.getExplanationText());
        response.setInputSnapshot(assessment.getInputSnapshot());
        response.setAssessedAt(assessment.getAssessedAt());
        response.setCreatedAt(assessment.getCreatedAt());
        response.setUpdatedAt(assessment.getUpdatedAt());
        return response;
    }

    private static class RiskScoreResult {
        private final double score;
        private final String level;
        private final List<String> topFactors;
        private final String explanationText;
        private final Map<String, Object> inputSnapshot;

        public RiskScoreResult(double score, String level, List<String> topFactors, String explanationText, Map<String, Object> inputSnapshot) {
            this.score = score;
            this.level = level;
            this.topFactors = topFactors;
            this.explanationText = explanationText;
            this.inputSnapshot = inputSnapshot;
        }

        public double getScore() { return score; }
        public String getLevel() { return level; }
        public List<String> getTopFactors() { return topFactors; }
        public String getExplanationText() { return explanationText; }
        public Map<String, Object> getInputSnapshot() { return inputSnapshot; }
    }
}